export const styles = {
    section: "py-32 px-4 bg-gradient-to-b from-slate-900 to-slate-950 overflow-hidden",
    container: "max-w-7xl mx-auto flex flex-col lg:flex-row items-center gap-20",
    content: "flex-1 space-y-10 relative z-10",
    title: "text-4xl md:text-6xl font-bold leading-tight tracking-tighter",
    titleBlue: "text-blue-500",
    description: "text-slate-400 text-xl leading-relaxed",
    featuresList: "space-y-6 pt-4",
    featureItem: "flex gap-5",
    featureNumber: "w-12 h-12 rounded-full bg-blue-900/30 flex items-center justify-center text-blue-400 font-bold shrink-0 border border-blue-500/20",
    featureTitle: "text-white font-bold text-lg",
    featureDesc: "text-slate-500",
    buttonWrapper: "pt-8",
    ctaButton: "bg-white text-slate-900 hover:bg-slate-200 font-bold px-10 h-14 text-lg",
    visualWrapper: "flex-1 w-full max-w-lg lg:max-w-none relative",
    glow: "absolute inset-0 bg-blue-600 blur-[120px] opacity-20 rounded-full animate-pulse",
    dashboard: "relative bg-slate-950 border border-slate-800 p-8 rounded-[2.5rem] shadow-2xl rotate-1 hover:rotate-0 transition duration-700 ease-out",
    dashboardHeader: "flex items-center justify-between mb-8 border-b border-slate-800 pb-6",
    dashboardInfo: "flex items-center gap-4",
    dashboardIconWrapper: "w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center text-white font-bold",
    dashboardTitle: "text-white font-bold text-lg",
    dashboardSubtitle: "text-slate-500 text-sm",
    dashboardStats: "text-green-500 font-bold text-2xl bg-green-500/10 px-4 py-2 rounded-xl border border-green-500/20",
    progressContainer: "space-y-6",
    progressLabel: "flex justify-between text-sm text-slate-400 mb-2",
    statusRed: "text-red-500 font-bold",
    statusBlue: "text-blue-500 font-bold",
    progressBarTrack: "w-full bg-slate-900 rounded-full h-3 border border-slate-800",
    progressBarFillRed: "bg-red-600 h-full rounded-full w-[15%] shadow-[0_0_10px_rgba(220,38,38,0.5)]",
    progressBarFillBlue: "bg-blue-600 h-full rounded-full w-[85%] shadow-[0_0_20px_rgba(37,99,235,0.6)] animate-pulse",
    alertBox: "mt-10 p-5 bg-slate-900 rounded-2xl border border-slate-800 flex gap-4 items-start",
    alertIcon: "text-slate-500 shrink-0 mt-1",
    alertText: "text-sm text-slate-400 leading-relaxed",
    whiteBold: "text-white font-bold",
};
